#!/bin/bash
set -e

# Servisi durdur ve devre dışı bırak
systemctl stop server-monitor
systemctl disable server-monitor

rm -rf "/usr/lib/python3/dist-packages/server_monitor/utils/__pycache__/" || true

exit 0
